import { createHmac, timingSafeEqual } from "node:crypto";

export const N8N_SIGNATURE_MAX_AGE_SECONDS = 300;

type VerifySignatureOptions = {
  nowMs?: number;
  maxAgeSeconds?: number;
};

function serializeJson(value: unknown): string {
  if (value === null || typeof value === "boolean" || typeof value === "string") {
    return JSON.stringify(value);
  }

  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new TypeError("Payload must contain valid JSON values.");
    return JSON.stringify(value);
  }

  if (Array.isArray(value)) {
    return `[${value.map(serializeJson).join(",")}]`;
  }

  if (typeof value === "object") {
    const record = value as Record<string, unknown>;
    return `{${Object.keys(record)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${serializeJson(record[key])}`)
      .join(",")}}`;
  }

  throw new TypeError("Payload must contain valid JSON values.");
}

/** Canonical JSON used by both the portal and n8n signature nodes. */
export function stableJson(value: unknown): string {
  return serializeJson(value);
}

export function signN8nPayload(
  payload: unknown,
  timestamp: string,
  secret: string,
): string {
  if (!secret) throw new TypeError("A signing secret is required.");

  return `sha256=${createHmac("sha256", secret)
    .update(`${timestamp}.${stableJson(payload)}`)
    .digest("hex")}`;
}

/**
 * Verifies the exact callback contract generated by n8n:
 * `timestamp + "." + stableJson(JSON.parse(rawBody))`.
 */
export function verifyN8nSignature(
  rawPayload: string,
  timestamp: string | null | undefined,
  signature: string | null | undefined,
  secret: string,
  options: VerifySignatureOptions = {},
): boolean {
  if (!secret || !timestamp || !signature) return false;
  if (!/^\d+$/.test(timestamp) || !/^sha256=[a-f\d]{64}$/i.test(signature)) {
    return false;
  }

  const timestampMs = Number(timestamp) * 1000;
  const nowMs = options.nowMs ?? Date.now();
  const maxAgeMs =
    (options.maxAgeSeconds ?? N8N_SIGNATURE_MAX_AGE_SECONDS) * 1000;
  if (!Number.isSafeInteger(timestampMs) || Math.abs(nowMs - timestampMs) > maxAgeMs) {
    return false;
  }

  try {
    const payload: unknown = JSON.parse(rawPayload);
    const expected = signN8nPayload(payload, timestamp, secret);
    const suppliedBuffer = Buffer.from(signature, "utf8");
    const expectedBuffer = Buffer.from(expected, "utf8");

    return (
      suppliedBuffer.length === expectedBuffer.length &&
      timingSafeEqual(suppliedBuffer, expectedBuffer)
    );
  } catch {
    return false;
  }
}
